language: c

cache: apt

sudo: required
dist: bionic

os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
compiler:
  - gcc
  - clang

matrix:
  exclude:
    # /usr/bin/gcc on OS X is clang, so it's not meaningful to build against both.
    - os: osx
      compiler: gcc
    - os: osx
      arch: ppc64le

addons:
  apt:
    sources:
#      - ubuntu-sdk-team
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libfftw3-dev
      - libliquid-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # cmake and pkg-config are already installed.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 fftw liquid-dsp; fi

script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_PREFIX_PATH=$(brew --prefix qt5)/lib/cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DYLIB_SUFFIX=dylib; else DYLIB_SUFFIX=so; fi
  - CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array" cmake ..
  - make
